<a href="https://colab.research.google.com/github/MaxKuzmenko/linear-algebra/blob/main/Linear%20algebra.%20Vector.%20HomeWork.%20KuzMax13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Линейная алгебра для нейросетей. Векторы.

## Подготовка:

In [ ]:
import numpy as np
from numpy.linalg import norm

In [ ]:
# Списки сущностей:
names = {
    0: "Элерон'Таз",
    1: "Чилит-в-Глубинах",
    2: "Ротгарн Стопа",
    3: "Ульфгард Золотая Струя",
    4: "Мурка",
    5: "Красная машина",
    6: "Носит-под-Гузник",
    7: "Куремар",
}

vec_list = np.array([
    [3, 9, 3, 0, 8, 2, 0, 4, 2],        # Элерон'Таз
    [2, 7, 4, 9, 8, 3, 0, 5, 4],        # Чилит-в-Глубинах
    [9, 3, 2, 0, 1, 8, 0, 5, 9],        # Ротгарн Стопа
    [7, 2, 3, 7, 4, 6, 0, 2, 6],        # Ульфгард Золотая Струя
    [5, 8, 1, 7, 2, 9, 0, 2, 3],        # Мурка
    [25, 10, 10, 0, 20, 30, 0, 0, 15],  # Красная машина
    [3, 3, 3, 3, 3, 3, 3, 3, 3],        # Носит-под-Гузник
    [1, 3, 9, 5, 1, 1, 0, 9, 1],        # Куремар
])

mods = [
    2.0,  # Зелье божественной силы
    1.2,  # Зелье могущества
    0.5,  # Сонливость
]

potions = np.array([
    [3, 0, 0, 0, 0, 0, 0, 0, 0],      # Зелье силы
    [2, 1, 0, 0, 0, 1, 0, 1, 1],      # Зелье война
    [-2, -1, 0, 0, 0, 0, 4, 0, -1],   # Яд паралича
    [0, 0, 3, 0, 0, 0, 0, 0, -1],     # Зелье ученого
    [1, 1, -1, 0, 0, 3, 0, 0, 1],     # Скама
    [0, 0, -2, -1, -1, 0, 0, 0, 1],   # Яд безумия
    [-2, 0, 0, 3, 1, 0, 0, -2, 0],    # Зелье красноречия
])

diseases = np.array([
    [-2, -2, -2, 0, -1, -3, 0, 1, 0],  # Простуда
    [1, 0, -1, -1, -1, 3, 9, 0, 0],    # Каменная хворь
    [-3, -1, 0, 1, -5, 0, 0, 3, 0],    # Чума
])

In [ ]:
# Таблица героев:
print(f'{'Имя:':<25} {'Очки навыков:':<15} {'Мощь:':<10}')
for i in range(len(vec_list)):
    points = norm(vec_list[i], ord=1)
    power = round(norm(vec_list[i], ord=2), 2)
    print(f'{names[i]:<25} {points:<15} {power:<10}')

Имя:                      Очки навыков:   Мощь:     
Элерон'Таз                31.0            13.67     
Чилит-в-Глубинах          42.0            16.25     
Ротгарн Стопа             37.0            16.28     
Ульфгард Золотая Струя    37.0            14.25     
Мурка                     37.0            15.39     
Красная машина            110.0           48.48     
Носит-под-Гузник          27.0            9.0       
Куремар                   30.0            14.14     


## Примеры операций:

### Умножение на скаляр:

In [ ]:
result = vec_list[0] * mods[1]
print(f"{vec_list[0]} * 1.3 = {result}")

[3 9 3 0 8 2 0 4 2] * 1.3 = [ 3.6 10.8  3.6  0.   9.6  2.4  0.   4.8  2.4]


### Сложение векторов:

In [ ]:
result = vec_list[0] + potions[0]
print(f"{vec_list[0]} + {potions[0]} = {result}")

[3 9 3 0 8 2 0 4 2] + [3 0 0 0 0 0 0 0 0] = [6 9 3 0 8 2 0 4 2]


### Норма:

In [ ]:
result = round(np.linalg.norm(vec_list[0], ord=2), 2)
print(f"{vec_list[0]} + {potions[0]} = {result}")

[3 9 3 0 8 2 0 4 2] + [3 0 0 0 0 0 0 0 0] = 13.67


### Скалярное произведение векторов:

In [ ]:
p_norm1_0 = norm(vec_list[0], ord=2)
p_norm1_1 = norm(vec_list[1], ord=2)
result = vec_list[0] @ vec_list[1] / (p_norm1_0 * p_norm1_1)
result = round(result, 2)

print(f"{vec_list[0]} * {vec_list[1]} = {result}")

[3 9 3 0 8 2 0 4 2] * [2 7 4 9 8 3 0 5 4] = 0.81


### Векторное произведение векторов:

In [ ]:
a = vec_list[0][:3]
b = vec_list[1][:3]
result = np.cross(a, b)

print(f"{a} * {b} = {result}")

[3 9 3] * [2 7 4] = [15 -6  3]


## Домашнее задание:

### Задание 1. Магический эксперимент.

Куремар решил провести эксперимент по расширению своих возможностей. Для этого он употребил все зелья из доступных (potions) и, как побочный эффект, получил модификатор сонливости.<p>
Вычислите изменение евклидовой нормы героя, чтобы узнать, стал ли он сильнее.

In [ ]:
# Вводные:
kuremar = vec_list[7].copy()
sleepiness = mods[2]
print(kuremar)

[1 3 9 5 1 1 0 9 1]


In [ ]:
# Решение:


### Задание 2. Вызов на бой.

Носит-под-Гузник мечтает одолеть Красную машину в бою. Помогите ему в этом.<p>
Наложите нужные модификаторы (mods, potions, diseases) на воинов так, чтобы евклидова норма вектора аутсайдера стала выше чем у противника.<p>
**Можно применить лишь по одному модификатору из каждого списка на одного героя.**<p>

In [ ]:
# Вводные:
nappy = vec_list[6].copy()
red_machine = vec_list[5].copy()
print(nappy, red_machine)

[3 3 3 3 3 3 3 3 3] [25 10 10  0 20 30  0  0 15]


In [ ]:
# Решение:


### Задание 3. Тест на совместимость.

Мурка решила найти себе подходящую пару. Она испробовала все лунные гороскопы совместимости, но так и не удовлетворилась результатом.<p>
Используйте векторный анализ, чтобы найти для нее наиболее похожего персонажа.<p>

In [ ]:
# Вводные:
murka = vec_list[4].copy()
print(murka)

[5 8 1 7 2 9 0 2 3]


In [ ]:
# Решение:


### Задание 4. Арена.

Настало время финальной битвы! Герои прибыли на знаменитую арену и разбились на команды. Все, кроме Красной машины, которого оштрафовали за слишком высокий параметр дерзости (его вектор = -1).
Перед тем как начнется битва, участникам предстоит сразиться с великаном, мощь которого равна 60. Те, кто одолеет испытание, пройдут в финальный раунд.

Разъяснение. Используя векторное умножение и евклидову норму, найдите все возможные пары героев и их суммарную мощь. Отсейте тех, кто не набрал 60 очков. Выясните, количество уникальных пар, прошедших в финал, а также, какая команда станет победителем соревнования.

Подведите итоги, сделав информативную статистику:

1. **Основные итоги.** Выведите топ уникальных пар, прошедших в финал в порядке убывания;

2. **Аутсайдеры.** Отдельным списком выведите тех, кто не прошел в финал ни в одной из команд;

3. **Линый результат.** Для каждого героя найдите сумму очков всех команд в которых он принимал участие. Выведите личный вклад героев (включая аутсайдеров) в порядке убывания.

Веди нас, Неревар!

In [ ]:
# Вводные:
vec_short_list = vec_list[:, :3].copy()
vec_short_list[5] = [-1, -1, -1]
threshold = norm([60, 0, 0], ord=2)

print(f"Мощь великана: {threshold}\n")
print(f"Таблица героев")
print(f'{'Имя:':<25}{'Сила:':<15}{'Ловкость:':<15}{'Интеллект:':<15}')
for i, row in enumerate(vec_short_list):
    print(f'{names[i]:<25}{row[0]:<15}{row[1]:<15}{row[2]:<15}')

Мощь великана: 60.0

Таблица героев
Имя:                     Сила:          Ловкость:      Интеллект:     
Элерон'Таз               3              9              3              
Чилит-в-Глубинах         2              7              4              
Ротгарн Стопа            9              3              2              
Ульфгард Золотая Струя   7              2              3              
Мурка                    5              8              1              
Красная машина           -1             -1             -1             
Носит-под-Гузник         3              3              3              
Куремар                  1              3              9              


In [ ]:
# Решение:
